version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "ci"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    vite:
      patterns:
      - "@vitejs/*"
      - "vite"
    vitest:
      patterns:
      - "@vitest/*"
      - "vitest"
    fastify:
      patterns:
      - "fastify"
      - "fastify-*"
      - "@fastify/*"
    react:
      patterns:
      - "react"
      - "react-dom"
      - "@types/react"
      - "@types/react-dom"
    mui:
      patterns:
      - "@mui/*"
    babel:
      patterns:
      - "@babel/*"
    eslint:
      patterns:
      - "eslint"
      - "eslint-plugin-*"
      - "eslint-config-*"
      - "@typescript-eslint/*"
    stylelint:
      patterns:
      - "stylelint"
      - "stylelint-config-*"
