version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.25.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
  - dependency-name: "@babel/eslint-plugin"
    versions:
    - 7.13.15
    - 7.13.16
  - dependency-name: "@material-ui/core"
    versions:
    - 5.0.0-alpha.26
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
    - 5.0.0-alpha.30
    - 5.0.0-alpha.31
  - dependency-name: "@material-ui/styles"
    versions:
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
    - 5.0.0-alpha.30
    - 5.0.0-alpha.31
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
    - 7.13.16
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.10.0
  - dependency-name: "@material-ui/icons"
    versions:
    - 5.0.0-alpha.26
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.15
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.15
  - dependency-name: find-cache-dir
    versions:
    - 3.3.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
  - dependency-name: "@babel/types"
    versions:
    - 7.13.13
    - 7.13.14
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.13.13
  - dependency-name: "@babel/plugin-transform-react-constant-elements"
    versions:
    - 7.13.13
  - dependency-name: "@babel/eslint-parser"
    versions:
    - 7.13.14
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
