name: Deploy Client

on:
  push:
    branches: [default]
    paths:
      - '.github/workflows/deploy-client.yml'
      - 'package.json'
      - 'client/**'
      - 'react-server-list/**'
  pull_request:
    branches: [default]
    paths:
      - '.github/workflows/deploy-client.yml'
      - 'package.json'
      - 'client/**'
      - 'react-server-list/**'

jobs:
  netlify:
    name: Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build client
        run: npm run -w client build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './client/dist'
          production-branch: 'default'
          github-token: ${{secrets.GITHUB_TOKEN}}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        timeout-minutes: 1
